pipeline {
    agent { label 'docker' }
    stages {
        // stage('Checkout') {
        //     steps {
        //         checkout scm
        //     }
        // }
        stage('Checkout Git') {
            steps { 
                checkout scm
                dir('../ANSIBLE') {
                    sh 'rm -rf *'
                    dir('devops-ansible-k8s-builds') { 
                        git credentialsId: 'git-repos', url: 'git@github.com:luiscarmignotto/devops-ansible-k8s-builds.git'
                    }
                    dir('devops-ansible-k8s-roles') { 
                        git credentialsId: 'git-repos', url: 'git@github.com:luiscarmignotto/devops-ansible-k8s-roles.git'
                    }                    
                }
            }
        }  
        stage('Getting Build Info') {
            steps {
                script {
                    def packageJson = readJSON file: 'package.json'
                    def appName = packageJson.name
                    def appVersion = packageJson.version
                    def registryUrl = packageJson.dockerRegistryUrl         
                    def imageName = "${appName}:${appVersion}"
                }
            }
        }
        stage('Updating Ansible Inventory') {
            steps {
                dir('../ANSIBLE/devops-ansible-k8s-builds') {
                    script {
                        def inventoryFile = 'inventory/group_vars/local_lab.yml'
                        def data = readYaml file: inventoryFile
                        data.solution.application.fipewatcher.image_tag = "${appVersion}"
                        sh "rm $inventoryFile"
                        writeYaml file: inventoryFile, data: data
                    }
                }

            }
        }    
        stage('Build') {
            steps {
                script {
                    sh "minikube image build -t ${imageName} ."
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('../ANSIBLE') {
                    sh 'ansible-playbook -i inventory/local_lab.yml site_install.yml'                    
                }
            }
        }
    }
}